name: Ubuntu

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add supported python versions here, don't forget to change it in the pyproject as well!
        python-version: ["3.9", "3.10", "3.11","3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        pip install .

    - name: Pytest
      run: |
        pip install pytest
        pytest .